/* Generated By:JavaCC: Do not edit this line. iCimpilirTreeConstants.java Version 5.0 */
package parser;

public interface iCimpilirTreeConstants
{
  public int JJTDAVAI = 0;
  public int JJTFUNCOES = 1;
  public int JJTPRINCIPAL = 2;
  public int JJTDECLARAVARAIAVEL = 3;
  public int JJTTIPO = 4;
  public int JJTATRIBUICAO = 5;
  public int JJTATRIBUIR = 6;
  public int JJTEXPRECAOLISTA = 7;
  public int JJTLOOPZAO = 8;
  public int JJTLISTAEXPRECAO = 9;
  public int JJTLISTAEXP2 = 10;
  public int JJTDECLARACAOM = 11;
  public int JJTEXPRECAO = 12;
  public int JJTFATOR = 13;
  public int JJTFATOR2 = 14;
  public int JJTSEQUNCIACOMANDOS = 15;
  public int JJTCOMANDO = 16;
  public int JJTELSE = 17;
  public int JJTEXPRECOESLOGICAS = 18;
  public int JJTFATORLOGICO = 19;
  public int JJTFUNC = 20;
  public int JJTLISTAARGUMENTOS = 21;
  public int JJTLISTA1ARGUMENTOS = 22;
  public int JJTLISTA2ARGUMENTOS = 23;


  public String[] jjtNodeName = {
    "Davai",
    "Funcoes",
    "Principal",
    "DeclaraVaraiavel",
    "Tipo",
    "Atribuicao",
    "Atribuir",
    "ExprecaoLista",
    "Loopzao",
    "ListaExprecao",
    "ListaExp2",
    "DeclaracaoM",
    "Exprecao",
    "Fator",
    "Fator2",
    "SequnciaComandos",
    "Comando",
    "Else",
    "ExprecoesLogicas",
    "FatorLogico",
    "Func",
    "ListaArgumentos",
    "Lista1Argumentos",
    "Lista2Argumentos",
  };
}
/* JavaCC - OriginalChecksum=f39488416d3d31d3da9c7367a96039c0 (do not edit this line) */
