/* Generated By:JJTree&JavaCC: Do not edit this line. iCimpilirConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface iCimpilirConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int COMENTARIOS = 6;
  /** RegularExpression Id. */
  int COM = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int ABRECHAVES = 9;
  /** RegularExpression Id. */
  int FECHACHAVES = 10;
  /** RegularExpression Id. */
  int ABREPARENTESES = 11;
  /** RegularExpression Id. */
  int FECHAPARENTESES = 12;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int PRINTF = 19;
  /** RegularExpression Id. */
  int FUNCAO = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int FLOAT = 22;
  /** RegularExpression Id. */
  int VIRGULA = 23;
  /** RegularExpression Id. */
  int ATRIBUICAO = 24;
  /** RegularExpression Id. */
  int OP = 25;
  /** RegularExpression Id. */
  int OPL = 26;
  /** RegularExpression Id. */
  int LETRA = 27;
  /** RegularExpression Id. */
  int DIGITO = 28;
  /** RegularExpression Id. */
  int DIGITOS = 29;
  /** RegularExpression Id. */
  int LD = 30;
  /** RegularExpression Id. */
  int FSUB = 31;
  /** RegularExpression Id. */
  int FOP = 32;
  /** RegularExpression Id. */
  int EXPOP = 33;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 34;
  /** RegularExpression Id. */
  int TOKEN_NUMLIT = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMENTARIO>",
    "<COMENTARIOS>",
    "<COM>",
    "\"principil\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"si\"",
    "\"sinii\"",
    "\"inquinti\"",
    "\"fici\"",
    "\"ritirni\"",
    "\"iscrivi\"",
    "\"fincii\"",
    "\"intiiri\"",
    "\"dicimil\"",
    "\",\"",
    "\"=\"",
    "<OP>",
    "<OPL>",
    "<LETRA>",
    "<DIGITO>",
    "<DIGITOS>",
    "<LD>",
    "<FSUB>",
    "<FOP>",
    "<EXPOP>",
    "<IDENTIFICADOR>",
    "<TOKEN_NUMLIT>",
  };

}
